name: Generate the NodeProp YAML Configuration File

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
job:
  generate-config:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate NodeProp Configuration
        id: nodeprop
        uses: ./  # Use the local action since we're in the action's repository
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: '.nodeprop.yml'
          storage-path: 'configs'

     - name: Commit Configuration
        run: |
          if [[ -n $(git status --porcelain .nodeprop.yml) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
            git add .nodeprop.yml
            git add configs/ || true
            
            # Create commit with detailed message
            git commit -m "Update NodeProp Configuration
            
            Hash: $(cat .nodeprop-hash)
            Generated by: ${{ github.workflow }}
            Event: ${{ github.event_name }}
            "
            
            # Push changes
            git push
          else
            echo "No changes to commit"
          fi

      # Create or update status check
      - name: Create Status Check
        if: success()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "state": "success",
              "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "description": "NodeProp configuration generated successfully",
              "context": "NodeProp/config"
            }' \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"

  notify:
    needs: generate-config
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Set Failed Status
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "state": "failure",
              "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "description": "Failed to generate NodeProp configuration",
              "context": "NodeProp/config"
            }' \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"